# Build and inspect the Python package
name: Check package

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 3 * *"

jobs:
  check-package:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      #- name: Remove the folders that are not a package and may confuse the build
      #  run: rm -rf learners

      - uses: hynek/build-and-inspect-python-package@v1

      - name: Setup Python
        uses: actions/setup-python@master

      - name: Install package requirements
        run: pip install -r requirements.txt

      - name: Install the package from the local code
        run: python3 -m pip install .

      - name: Run the code
        run: python3 main.py

      #- name: Run console application
      #  run: ./scripts/run_console.sh

      #- name: Run GUI application
      #  run: ./scripts/run_gui_application.sh

      #- name: Run benchmarks
      #  run: ./scripts/run_benchmarks.sh
